services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_NAME: LOCAL
      APP_PORT: 3000
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ddd_nest_api
      DB_SYNC: 'false'
      JWT_SECRET: local-secret
      TOKEN_EXPIRATION: 1000d
    ports:
      - '3000:3000'
    volumes:
      - ./storages:/app/storages

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddd_nest_api
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ddd_nest_api']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
